server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel控制台服务地址
        port: 8739 #默认8719，被占用则+1,此端口用于和nacos通信进行数据交换
      web-context-unify: false #上下文是否是同一个链路，即默认controller调用service是同一个链路
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow